// entertainment_web_app/src/pages/Login.jsx
import { useEffect, useState } from "react";
import {
  useLocation,
  useNavigate,
  useNavigationType,
  Link,
  useParams,
  useSearchParams,
} from "react-router-dom";

import Logo from "../assets/logo.svg";
import Button from "../components/Button";

const Login = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const [params, setParams] = useSearchParams({});
  const navigateType = useNavigationType();
  const signup = location.pathname.includes("signup");
  const [firstSign, setFirstSign] = useState(true);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [repeatPwd, setReapeatPwd] = useState("");

  function login(e) {
    e.preventDefault();

    if (password === repeatPwd) {
      fetch("http://localhost:3100/signup", {
        method: "POST",
        mode: "cors",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email,
          password,
        }),
      })
        .then((res) => (res.status === 200 ? res.text() : null))
        .then((data) => {
          navigate("/login?success=true");
          setFirstSign(true);
          setEmail("");
          setPassword("");
          setReapeatPwd("");
        })
        .catch((err) => console.log(err));
    }
  }

  useEffect(() => {
    setParams({ sucess: "true" });
    console.log(params);
  }, []);

  return (
    <div className="login">
      <img src={Logo} alt="Logo" />
      <form onSubmit={login}>
        {signup ? <h1>Sign Up</h1> : <h1>Login</h1>}
        {firstSign ? (
          <div>
            <h3 className="success">Account created</h3>
          </div>
        ) : (
          ""
        )}
        <div>
          <input
            type="email"
            value={email}
            placeholder="Email address"
            onChange={(e) => setEmail(e.target.value)}
          />
        </div>
        <div>
          <input
            type="password"
            value={password}
            placeholder="Password"
            onChange={(e) => setPassword(e.target.value)}
          />
        </div>
        {signup && (
          <div>
            <input
              type="password"
              value={repeatPwd}
              placeholder="Repeat password"
              onChange={(e) => setReapeatPwd(e.target.value)}
            />
          </div>
        )}
        <Button text={signup ? "Sign Up" : "Login"} type={"submit"} />
        {signup ? (
          <p>
            Already have an account? <Link to={"/login"}>Login</Link>
          </p>
        ) : (
          <p>
            Don't have an account? <Link to={"/signup"}>Sign Up</Link>
          </p>
        )}
      </form>
    </div>
  );
};

export default Login;

// entertainment-web-app/frontend/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { AppUser } from '../utils';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
})
export class LoginComponent implements OnInit {
  url!: string;
  signUp!: boolean;
  email: string = '';
  password: string = '';
  rpassword: string = '';

  constructor(private route: ActivatedRoute) {}

  ngOnInit(): void {
    this.route.url.subscribe((url) => (this.url = url[0]?.path));
    this.signUp = this.loginHandler(this.url);
  }

  loginHandler(currentUrl: string): boolean {
    if (currentUrl === 'signup') {
      return true;
    }

    return false;
  }

  handleAuth(): void {
    if (this.loginHandler(this.url)) {
      if (this.password.trim() === this.rpassword.trim()) {
        const User = new AppUser(this.email, this.password);

        fetch('http://localhost:3000/api/user', {
          method: 'POST',
          headers: {
            // prettier-ignore
            'Content-Type': "application/json",
          },
          body: JSON.stringify(User),
        })
          .then((res) =>
            res.status === 200 ? console.log(res.statusText) : null
          )
          .catch((err) => console.error(err));
      }
    }
    console.log(this.loginHandler(this.url));

    // console.log(User.getUser());
    // setTimeout(() => {
    //   this.email = '';
    // }, 10000);
    // setTimeout(() => {
    //   console.log(this.email);
    // }, 15000);
  }
}

<main class="login-container">
  <div class="login">
    <img src="../../assets/logo.svg" alt="EntertainmentWebApp" />
    <div>
      <h1>{{ signUp ? "Sign Up" : "Login" }}</h1>
      <form (submit)="handleAuth()">
        <div>
          <input
            type="email"
            name="email"
            id="email"
            placeholder="Email address"
            required
            [(ngModel)]="email"
            [value]="email"
          />
        </div>
        <div>
          <input
            type="password"
            name="password"
            id="password"
            placeholder="Password"
            required
            [(ngModel)]="password"
            [value]="password"
          />
        </div>
        <div *ngIf="signUp">
          <input
            type="password"
            name="password"
            id="password"
            placeholder="Repeat Password"
            required
            [(ngModel)]="rpassword"
            [value]="rpassword"
          />
        </div>
        <button class="btn btn-primary">
          {{ signUp ? "Create an account" : "Login to your account" }}
        </button>
      </form>
      <p>
        {{ signUp ? "Already have an account?" : "Don't have an account?" }}
        <a *ngIf="signUp; else elseB" routerLink="/login">Login</a>
        <ng-template #elseB><a routerLink="/signup">SignUp</a></ng-template>
      </p>
    </div>
  </div>
</main>
